### ISSUE TITLE
thanks :)

### ISSUE THREAD

**Issue by BKSpurgeon** [davidgf/design-patterns-in-ruby#3]
but this is a wonderful thing you have put together, thanks for doing it.

rgds

Ben

**Comment by davidgf** [comment]
Thank you, both for your message and for contributing! 😄

**Comment by elissonmichael** [comment]
@davidgf I want to thank you too.

I would like to ask if you would accept a Pull Request containing a Brazilian Portuguese Translation.

**Comment by davidgf** [comment]
@elissonmichael absolutely, that would be very much appreciated :slightly_smiling_face:
